### ISSUE TITLE
Make checkboxes properly visible while not allowing them to be clicked

### ISSUE THREAD

**Issue by ianholst** [yzhang-gh/vscode-markdown#1188]
In the Markdown Preview, it's very hard to distinguish checked and unchecked items in task lists, making this feature not very useful. It's particularly bad on a dark background:

![checkboxes](https://user-images.githubusercontent.com/2507974/197914203-6c81b249-90b2-4d8d-8e9c-91d395fdeecc.png)

This is because the checkbox elements are set as `disabled` by the Markdown parser. Of course, I understand that you don't want them to actually be clickable because clicking won't change the source and that's confusing. I propose a solution by changing the following:

In `vscode-markdown/src/markdown-it-plugin-provider.ts`, change
```ts
md.use(require("markdown-it-task-lists"));
```
to
```ts
md.use(require("markdown-it-task-lists"), {enabled: true});
```
as suggested in #192.

The clickability is solved by changing `vscode-markdown/media/checkbox.css`:
```css
.task-list-item-checkbox {
    margin-left: -20px;
    vertical-align: middle;
    pointer-events: none; /* add this line */
}
```

This prevents any interaction with the checkboxes while still rendering them visible and useful.

I've confirmed that this works in VS Code. I can try to figure out how to make a pull request for this if that would help.
