### ISSUE TITLE
Slugify rules for MkDocs

### ISSUE THREAD

**Issue by willsansbury** [yzhang-gh/vscode-markdown#1502]
### Proposal

Please support MkDocs slugify rules.

In MkDocs, if I have a heading like:
`# Step 1 - Do This`

Mkdocs slugifies it to:
`#step-1-do-this`

None of the existing options were collapsing multiple hyphens into one like MkDocs does:
`#step-1---do-this`

**Comment by smainz** [comment]
I do not know what the default slugify rules for MKDocs are, so I can not provide a PR.

But you can make MkDocs use a different slugify algorithm in your `mkdocs.yml`

```yaml
markdown_extensions:
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
```

Not the best solution, as you have to change all your existing links and tweak mkdocs for your editor.


If someone points me to the correct mkdocs slugify algorithm I could try a PR though.
