### ISSUE TITLE
能否针对中文段落增加首行缩进显示？

### ISSUE THREAD

**Issue by wenda84** [yzhang-gh/vscode-markdown#958]
## Proposal
中文没有首行缩进，看起来很不爽。目前网上的方法，要么是加全角空格，要么就是插入nbsp，都很割裂。与使用md的初衷就违背了。

**Comment by Lemmingh** [comment]
```css
p:lang(zh)::before {
    content: "\3000\3000";
}
```
